apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: orbitelco.dev
      http:
        paths:
          - path: /api/users/v2/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/products/v2/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: products-srv
                port:
                  number: 3000
          - path: /api/orders/v2/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: orders-srv
                port:
                  number: 3000
          - path: /api/idsequence/v2/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: seq-srv
                port:
                  number: 3000
          - path: /api/seeddata/v2/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: seed-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
